version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
    volumes:
      - ./:/app:cached
    env_file:
      - ./.env
    working_dir: /app
    # command: npm run start:dev
    command: npx nodemon --legacy-watch --config nodemon.json
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.26
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - 3306:3306
    volumes:
      - "./data/mysql:/var/lib/mysql"

networks:
  ayebashit:
    external: true
