version: "3.8"

services:
  telegram-io:
    build:
      context: ./telegram-io
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
    volumes:
      - ./telegram-io:/app:cached
    env_file:
      - .env
    working_dir: /app
    command: npx nodemon --legacy-watch --config nodemon.json
    depends_on:
      - mysql
      - redis
      - wb-stats

  wb-stats:
    build:
      context: ./wb-stats
      dockerfile: Dockerfile.dev
    volumes:
      - ./wb-stats:/app:cached
    env_file:
      - .env
    working_dir: /app
    command: npx nodemon --legacy-watch --config nodemon.json
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0.26
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - 3306:3306
    volumes:
      - "./data/mysql:/var/lib/mysql"

  redis:
    image: redis:6



networks:
  mp-bot:
    external: true
