apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp_bot
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hub.triadium.ru/ayebashit/backend:{{ .Values.version }}
          command: ["npm", "run", "start:prod"]
          ports:
            - containerPort: 4200
          env:
            - name: LOGZ_API_KEY
              value: logz-api-key
            - name: JWT_SECRET
              value: jwt-secret
            - name: MAILGUN_API_KEY
              value: mailgun-api-key
            - name: MYSQL_HOST
              value: 'mysql'
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: mysql-user
            - name: MYSQL_PASSWORD
              value: mysql-password
            - name: MYSQL_DATABASE
              value: mysql-database
      imagePullSecrets:
        - name: hub.triadium.ru

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hub.triadium.ru/ayebashit/frontend:{{ .Values.version }}
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: hub.triadium.ru

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0.24
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_USER
              value: mysql-user
            - name: MYSQL_PASSWORD
              value: mysql-password
            - name: MYSQL_DATABASE
              value: mysql-database
            - name: MYSQL_ROOT_PASSWORD
              value: mysql-root-password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: ps-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: ps-mysql
          persistentVolumeClaim:
            claimName: pvc-mysql
