apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-bot
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vosyukov/mp_bot:{{ .Values.version }}
          command: ["npm", "run", "start:prod"]
          ports:
            - containerPort: 4200
          env:
            - name: MYSQL_HOST
              value: 'mysql'
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: mysql-user
                  name: db-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: db-secret
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: mysql-database
                  name: db-secret
            - name: TG_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: tg-secret
            - name: YOOKASSA_ID
              valueFrom:
                secretKeyRef:
                  key: id
                  name: yookassa-secret
            - name: YOOKASSA_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: yookassa-secret
      imagePullSecrets:
        - name: regcred

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0.24
          name: mysql
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: mysql-user
                  name: db-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: db-secret
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: mysql-database
                  name: db-secret
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-root-password
                  name: db-secret
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: ps-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: ps-mysql
          persistentVolumeClaim:
            claimName: pvc-mysql
