apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: mp-bot-nginx-r
spec:
  controller: k8s.io/ingress-nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mp-bot-ingress
spec:
  tls:
    - hosts:
        - pay.wb-bot.fun
      secretName: mp-bot-tls-secret
  rules:
    - host: "pay.wb-bot.fun"
      http:
        paths:
          - pathType: Prefix
            path: "/callback"
            backend:
              service:
                name: backend-service
                port:
                  number: 4200

  ingressClassName: mp-bot-nginx-r

---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: mp-bot-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: mp-bot-letsencrypt
    solvers:
      - http01:
          ingress:
            class: mp-bot-nginx-r

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mp-bot-le-crt
spec:
  secretName: mp-bot-tls-secret
  issuerRef:
    kind: Issuer
    name: mp-bot-letsencrypt
  commonName: pay.wb-bot.fun
  dnsNames:
    - pay.wb-bot.fun
