apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 4200
  selector:
    app: backend

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
    - port: 80
  selector:
    app: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
