FROM node:lts-alpine
RUN apk add --update --no-cache build-base make python3

WORKDIR /app

COPY ["package.json", "package-lock.json", "tsconfig.json", "tsconfig.build.json", "nest-cli.json", ".eslintrc.js", "./"]
RUN npm ci
COPY src src
COPY templates templates