name: Deploy to production

on:
  push:
    tags:
      - '*'
jobs:

  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: lint helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint .helm

#  tests:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build test image
#        uses: docker/build-push-action@v2.4.0
#        with:
#          file: Dockerfile.test
#          push: false
#          tags: 'test_image'
#      - name: tests
#        run: docker run test_image npx jest

  build-telegram-io:
    needs: [lint-helm]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.HUB_REGISTRY_USER}}
          password: ${{secrets.HUB_REGISTRY_TOKEN}}
      - name: set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push backend image
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./telegram-io
          push: true
          tags: vosyukov/mp_bot-telegram-io:${{ env.RELEASE_VERSION }}

  build-api:
    needs: [lint-helm]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.HUB_REGISTRY_USER}}
          password: ${{secrets.HUB_REGISTRY_TOKEN}}
      - name: set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push backend image
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./api
          push: true
          tags: vosyukov/mp_bot-api:${{ env.RELEASE_VERSION }}



  deployment:
    needs: [build-api, build-telegram-io]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade mp-bot .helm/ --install --create-namespace --wait --atomic --version ${GITHUB_REF##*/} --namespace=mp-bot --set version=${GITHUB_REF##*/}
          kubeconfig: ${{ secrets.KUBECONFIG }}
